name: CI

on:
  push:
    branches: ['*']  # Trigger on push events for all branches
  pull_request:
    branches: ['master']  # Trigger on pull requests to master
  workflow_dispatch:  # Allow manual triggering of workflow

jobs:
  build:
    if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
    uses: ./.github/workflows/cmake.yml
    with:
      build_type: Debug

  build_pr:
    if: github.event_name == 'pull_request' && github.event.pull_request.base.ref == 'master'
    strategy:
      matrix:
        build_type: [Debug, Release]
    uses: ./.github/workflows/cmake.yml
    with:
      build_type: ${{ matrix.build_type }}
