name: CI

on:
  push:
    branches: ['*']  # Trigger on push events for all branches
    tags-ignore: ['*']  # Ignore push events on all tags
  pull_request:
    branches: ['main']  # Trigger on pull requests to main
  workflow_dispatch:  # Allow manual triggering of workflow

jobs:
  build:
    uses: ./.github/workflows/cmake.yml
    with:
      build_type: '"Release"'
      upload_artifacts: true